name: Build iOS IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: ls

      - name: Build archive
        run: |
          xcodebuild \
          -project NativeQR.xcodeproj \
          -scheme NativeQR \
          -configuration Release \
          -sdk iphoneos \
          -destination 'generic/platform=iOS' \
          -archivePath build/NativeQR.xcarchive \
          archive \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""

      - name: Create IPA
        run: |
          mkdir Payload
          cp -r build/NativeQR.xcarchive/Products/Applications/*.app Payload/
          zip -r NativeQR.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: NativeQR.ipa
